# A detailed description for all parameters can be found in BenchmarkOptions.h

parameters:
    name: FullBenchmark
    runs: 1
    group: panda_arm      # Required
    timeout: 1.5
    output_directory: /tmp/moveit_benchmarks/
    start_states_regex: ready
planning_pipelines:
  # Benchmark tool
  pipelines: [OMPL_ANY, OMPL_RRTC, CHOMP, PILZ_LIN]
  OMPL_ANY:
     name: ompl
     planners:
       - APSConfigDefault
  OMPL_RRTC:
    name: ompl_rrtc
    planners:
      - RRTConnectkConfigDefault
  CHOMP:
     name: stomp
     planners:
       - stomp
  PILZ_LIN:
     name: pilz_industrial_motion_planner
     planners:
       - LIN
  parallel_pipelines: [ompl_pilz_chomp]
  ompl_pilz_chomp:
    pipelines: [ompl_rrtc, stomp, pilz_industrial_motion_planner]
    planner_ids: [RRTConnectkConfigDefault, stomp, LIN]
