# Example command:
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=main-rolling-tutorial-source compose run cpu

x-common: &common-service
  #image: moveit/moveit2:main-jazzy-tutorial-source
  image: d130s/ros:moveit2-main-jazzy-tutorial-source  # TEMPORARY dev
  privileged: true
  network_mode: host
  command: /bin/bash
  tty: true
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - $XAUTHORITY:/root/.Xauthority
  environment:
    &common-env
    QT_X11_NO_MITSHM: 1
    DISPLAY: $DISPLAY

services:
  cpu:
    <<: *common-service
    container_name: moveit2_container_cpu
    profiles:
      - cpu
  gpu:
    <<: *common-service
    container_name: moveit2_container_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      <<: *common-env
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
