# Docker Compose file for Isaac ROS2 Control
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <name>
#
# To open an interactive shell to a running container:
# (You can tab complete to get the container name)
#   docker exec -it <container_name> bash

services:
  base:
    image: isaac_moveit_tutorial
    build:
      context: .
      dockerfile: .docker/Dockerfile
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID
      # Allows graphical programs in the container
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:      
      # Allows graphical programs in the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # Allows GPU access -- comment out this block if you don't have one
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: /bin/bash
