controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robotiq_gripper_controller:
      type: parallel_gripper_action_controller/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

robotiq_gripper_controller:
  ros__parameters:
    joint: finger_joint
