name: CheckBuildHTML

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-html:
    name: CheckBuildHTML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Run htmlproofer.sh
      run: ./htmlproofer.sh
